var gulp = require('gulp')
var concat = require('gulp-concat')
var uglify = require('gulp-uglify')
var minifyCSS = require('gulp-minify-css')
var rename = require('gulp-rename')
var notify = require('gulp-notify')
var webserver = require('gulp-webserver')
gulp.task("first",function(){
    gulp.src('./*')
        .pipe(concat('./he.js'))
        .pipe(rename({suffix:".min"}))
        .pipe(minifyCSS())
        .pipe(gulp.dest('./'))
})
